### ISSUE TITLE
Ok there is a very tiny prob.

### ISSUE THREAD

**Issue by crunkazcanbe** [coolsquid/SquidAPI#1]
Every since the stopmodreposts.org website came out I knew mods would try to implement something into there mods to stop people from illegally getting there mods , and I am all for this , but the problem in doing this does more harm then good to the legit people such as my self .

I download SquidAPI-1.0.4 and SquidUtils-1.1.7 from curse , and am seeing this very very annoying pop up that says 

SquidAPI has detected mods downloaded through an illegal website.
To fix this error, download the **latest** official version from: http://coolsquid.wix.com/software#!downloads/cppf.

Unauthorised mods:
SquidAPI

Proudly supporting #StopModReposts!
http://stopmodreposts.org/

Do you believe this is an error? Report it at:
https://github.com/coolsquid/SquidAPI/issues

Well It keeps my game from auto going full screen and its super annoying . I say this because I am legit , and always get mods from curse or minecraftforums , and I don't like to be punished for others problems . I am very sorry If I came out as being mean because I am not a mean person . I love your mods . :)

Thank you!

-Crunk

**Comment by coolsquid** [comment]
Fixed already. Sorry for that!
